// Manager employee page: tap a knowledge block to reveal test / attestation actions.
state.expandedKnowledgeKey=state.expandedKnowledgeKey||'';
function knowledgeKey(area,block){return area+'::'+block}
function toggleKnowledge(area,encodedBlock){const block=decodeURIComponent(encodedBlock),key=knowledgeKey(area,block);state.expandedKnowledgeKey=state.expandedKnowledgeKey===key?'':key;save();render()}
function assignTestPlaceholder(area,encodedBlock){const block=decodeURIComponent(encodedBlock);openModal(`<div class="modal-head"><div><div class="kicker">Назначить тест</div><h2>${esc(block)}</h2><p>${area==='kitchen'?'Кухня':'Бар'}</p></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="notice">Механику назначения и прохождения тренировочного теста проектируем отдельно. Зафиксировано правило: тренировочный тест рейтинг не меняет.</div>`)}
function runAttestationPlaceholder(id,area,encodedBlock){const block=decodeURIComponent(encodedBlock);attestationPlaceholder(id,area,block)}
function knowledgeRows(e,area){return blocksFor(area).map(b=>{const r=rating(e,area,b),n=atts(e,area,b).length,key=knowledgeKey(area,b),open=state.expandedKnowledgeKey===key,enc=encodeURIComponent(b);const desc=n?`${n} аттестаци${n===1?'я':'и'}${r?' · текущий результат '+r+'%':''}`:'Аттестаций пока нет';const actionLabel=n?'Провести аттестацию':'Провести первую аттестацию';return `<div class="knowledge-row-wrap ${open?'open':''}"><button class="knowledge-row" onclick="toggleKnowledge('${area}','${enc}')"><div><b>${esc(b)}</b><small>${esc(desc)}</small></div><strong>${r?r+'%':'—'}</strong><span class="knowledge-chevron">›</span></button><div class="knowledge-expand"><div class="knowledge-expand-inner"><div class="knowledge-explain"><b>${n?'Блок уже участвует в рейтинге':'Рейтинг по блоку ещё не сформирован'}</b><small>${n?'Можно назначить тренировку или провести новую аттестацию.':'Назначь тренировочный тест или проведи первую аттестацию.'}</small></div><div class="knowledge-actions"><button class="ghost" onclick="assignTestPlaceholder('${area}','${enc}')">Назначить тест</button><button class="primary" onclick="runAttestationPlaceholder('${e.id}','${area}','${enc}')">${actionLabel}</button></div></div></div></div>`}).join('')}
function openEmployeePage(id){state.currentEmployee=id;state.route='employee-detail';state.expandedKnowledgeKey='';save();closeModal();render();window.scrollTo({top:0,behavior:'smooth'})}
render();
