function renderManager(){if(state.route==='team')return managerTeam();if(state.route==='rating')return ratingPage();if(state.route==='ideas')return deferredPage();return managerHome()}
function managerHome(){return `<section class="managerhero"><div class="kicker">Управляющий · кабинет</div><h1>Команда и подтверждённые знания</h1><p>Здесь нет рейтинга за тренировки. Итоговые цифры собираются из нескольких аттестаций сотрудников.</p><div class="split-actions"><button class="primary" onclick="go('team')">Открыть команду</button><button class="ghost" onclick="openEmployeeForm()">Добавить сотрудника</button></div></section><section class="section"><div class="grid g3"><div class="card metric"><span>Рейтинг команды</span><strong>${teamRating()||'—'}${teamRating()?'%':''}</strong><small>Среднее по сотрудникам с аттестациями</small></div><div class="card metric"><span>Сотрудники</span><strong>${state.employees.length}</strong><small>Официанты и бармены</small></div><div class="card metric"><span>Аттестации</span><strong>${state.employees.reduce((s,e)=>s+atts(e).length,0)}</strong><small>История сохраняется отдельно по каждому сотруднику</small></div></div></section><section class="section"><div class="head"><div><h2>Требуют внимания</h2><p>Низкий средний результат аттестаций</p></div></div><div class="team-grid">${[...state.employees].sort((a,b)=>rating(a)-rating(b)).slice(0,2).map(employeeCard).join('')}</div></section>`}
function managerTeam(){return `<div class="head"><div><h2>Команда</h2><p>Сотрудники, рейтинги и управление</p></div><button class="primary" onclick="openEmployeeForm()">+ Сотрудник</button></div><div class="team-grid">${state.employees.map(employeeCard).join('')}</div>`}
function employeeCard(e){return `<div class="card employee">${employeePhoto(e)}<div><h3>${esc(e.name)}</h3><p>${esc(e.role)} · с ${esc(e.start||'—')}<br>${esc(e.phone||'')} ${e.tg?'· '+esc(e.tg):''}</p><div class="emp-ratings"><span class="mini-rating">Кухня ${rating(e,'kitchen')||'—'}%</span><span class="mini-rating">Бар ${rating(e,'bar')||'—'}%</span><span class="mini-rating">${atts(e).length} атт.</span></div></div><div class="emp-score"><strong>${rating(e)||'—'}${rating(e)?'%':''}</strong><span>${status(rating(e))}</span></div><div class="employee-actions"><button class="primary" onclick="openEmployeeManager('${e.id}')">Управление</button><button class="ghost" onclick="openEmployeeForm('${e.id}')">Редактировать</button></div></div>`}
function openEmployeeManager(id){state.currentEmployee=id;save();const e=emp(id),kr=rating(e,'kitchen'),br=rating(e,'bar');openModal(`<div class="modal-head"><div><div class="kicker">Управление сотрудником</div><h2>${esc(e.name)}</h2><p>${esc(e.role)} · рейтинг ${rating(e)||'—'}${rating(e)?'%':''} · ${atts(e).length} аттестаций</p></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="grid g2" style="margin-top:14px">${manageArea(e,'kitchen','Кухня',kr)}${manageArea(e,'bar','Бар',br)}</div><section class="section"><div class="head"><div><h2 style="font-size:16px">История аттестаций</h2><p>Именно эти результаты формируют рейтинг</p></div></div>${attList(e,20)}</section><section class="section"><div class="head"><div><h2 style="font-size:16px">Доступ сотрудника</h2><p>PIN меняется здесь, внутри карточки сотрудника</p></div></div><div class="card" style="box-shadow:none"><div class="split-actions"><button class="ghost" onclick="openPinReset('${e.id}')">Сменить / сбросить PIN</button><button class="ghost" onclick="openEmployeeForm('${e.id}')">Редактировать данные</button></div></div></section>`)}
function manageArea(e,area,title,r){return `<div class="card" style="box-shadow:none"><div class="area-top"><div><span class="badge">${title}</span><h3>${title}</h3></div><b>${r?r+'%':'—'}</b></div><div class="track" style="margin:10px 0"><i style="width:${r}%"></i></div><div class="blocks">${blocksFor(area).map(b=>`<div class="blockrow"><div><b>${esc(b)}</b><small>${atts(e,area,b).length} атт. · ${rating(e,area,b)||'—'}%</small></div><button class="primary" onclick="openAttestation('${e.id}','${area}','${esc(b)}')">Аттестация</button></div>`).join('')}</div></div>`}
function attList(e,limit){const rows=[...atts(e)].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit);if(!rows.length)return `<div class="empty">Аттестаций пока нет.</div>`;return `<div class="list">${rows.map(a=>`<div class="att-row"><div><b>${esc(a.block)}</b><small>${a.area==='kitchen'?'Кухня':'Бар'} · ${esc(a.date)}</small></div><span class="badge ${a.score>=85?'ok':a.score<70?'warn':''}">${status(a.score)}</span><div class="att-score">${a.score}%</div></div>`).join('')}</div>`}
function openAttestation(id,area,block){const e=emp(id);openModal(`<div class="modal-head"><div><div class="kicker">Новая аттестация</div><h2>${esc(e.name)}</h2><p>${area==='kitchen'?'Кухня':'Бар'} · ${esc(block)}</p></div><button class="closebtn" onclick="openEmployeeManager('${id}')">×</button></div><div class="notice">Это аттестация, поэтому её результат войдёт в рейтинг как ещё одна отдельная оценка. Рейтинг будет средним из накопленных аттестаций.</div><div class="form"><div class="field"><label>Результат, %</label><input id="attScore" type="number" min="0" max="100" value="85"></div><div class="field"><label>Дата</label><input id="attDate" type="date" value="${today()}"></div></div><div class="modal-actions"><button class="primary" onclick="saveAttestation('${id}','${area}','${esc(block)}')">Сохранить аттестацию</button></div>`)}
function saveAttestation(id,area,block){const score=Math.max(0,Math.min(100,Number(document.getElementById('attScore').value)||0));const date=document.getElementById('attDate').value||today();const e=emp(id);e.attestations=e.attestations||[];e.attestations.push({id:'a'+Date.now(),area,block,score,date});save();render();openEmployeeManager(id)}
function openEmployeeForm(id=null){const e=id?emp(id):{name:'',role:'Официант',phone:'',tg:'',start:today(),pin:'',photo:''};openModal(`<div class="modal-head"><div><div class="kicker">${id?'Редактирование':'Новый сотрудник'}</div><h2>${id?esc(e.name):'Добавить сотрудника'}</h2><p>Основные данные и доступ.</p></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="form"><div class="field full"><label>Имя и фамилия</label><input id="empName" value="${esc(e.name)}"></div><div class="field"><label>Роль</label><select id="empRole"><option ${e.role==='Официант'?'selected':''}>Официант</option><option ${e.role==='Бармен'?'selected':''}>Бармен</option></select></div><div class="field"><label>Дата начала</label><input id="empStart" type="date" value="${esc(e.start||today())}"></div><div class="field"><label>Телефон</label><input id="empPhone" value="${esc(e.phone||'')}"></div><div class="field"><label>Telegram</label><input id="empTg" value="${esc(e.tg||'')}"></div><div class="field"><label>PIN, 4 цифры</label><input id="empPin" inputmode="numeric" maxlength="4" value="${esc(e.pin||'')}"></div><div class="field"><label>Фото сотрудника</label><input id="empPhoto" type="file" accept="image/*" onchange="previewEmployeePhoto(this)"></div><div class="field full"><div id="photoPreview" class="small-muted">${e.photo?'Фото уже сохранено. Новое заменит его.':'Фото можно добавить сейчас или позже.'}</div></div></div><div class="modal-actions">${id?`<button class="danger" onclick="deleteEmployee('${id}')">Удалить</button>`:''}<button class="primary" onclick="saveEmployee('${id||''}')">Сохранить</button></div>`)}
let pendingPhoto=null;
function previewEmployeePhoto(input){const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingPhoto=r.result;document.getElementById('photoPreview').innerHTML='<span class="badge ok">Фото готово к сохранению</span>'};r.readAsDataURL(f)}
function saveEmployee(id){const name=document.getElementById('empName').value.trim();if(!name){alert('Укажите имя');return}const data={name,role:document.getElementById('empRole').value,start:document.getElementById('empStart').value,phone:document.getElementById('empPhone').value.trim(),tg:document.getElementById('empTg').value.trim(),pin:document.getElementById('empPin').value.trim().slice(0,4)};if(id){Object.assign(emp(id),data);if(pendingPhoto)emp(id).photo=pendingPhoto}else{state.employees.push({id:'e'+Date.now(),...data,photo:pendingPhoto||'',attestations:[]})}pendingPhoto=null;save();closeModal();render()}
function deleteEmployee(id){if(!confirm('Удалить сотрудника из демо?'))return;state.employees=state.employees.filter(e=>e.id!==id);if(state.currentEmployee===id)state.currentEmployee=state.employees[0]?.id||'';save();closeModal();render()}
function openPinReset(id){const e=emp(id);openModal(`<div class="modal-head"><div><div class="kicker">Доступ сотрудника</div><h2>${esc(e.name)}</h2><p>PIN меняет управляющий из карточки конкретного сотрудника.</p></div><button class="closebtn" onclick="openEmployeeManager('${id}')">×</button></div><div class="form"><div class="field full"><label>Новый PIN, 4 цифры</label><input id="newPin" inputmode="numeric" maxlength="4" value="${esc(e.pin||'')}"></div></div><div class="modal-actions"><button class="primary" onclick="savePin('${id}')">Сохранить PIN</button></div>`)}
function savePin(id){const pin=document.getElementById('newPin').value.replace(/\D/g,'').slice(0,4);if(pin.length!==4){alert('Нужно 4 цифры');return}emp(id).pin=pin;save();render();openEmployeeManager(id)}
function deferredPage(){return `<section class="managerhero"><div class="kicker">Отложено намеренно</div><h1>Главные продуктовые вопросы — отдельно</h1><p>Мы не маскируем незаконченные решения случайной логикой. Два пункта вынесены в рабочую таблицу идей.</p></section><section class="section"><div class="grid g2"><div class="card"><span class="badge warn">Главная фишка</span><h3>Механика тренировок и аттестаций</h3><p class="small-muted">Отдельно решить типы вопросов, повторения, ошибки, историю попыток, правила аттестации и сбор нескольких аттестаций в рейтинг.</p></div><div class="card"><span class="badge">Идея / позже</span><h3>Актуализация знаний при изменении меню</h3><p class="small-muted">Что происходит при изменении блюда, состава, цены или появлении новой позиции. В эту версию не внедрено.</p></div></div></section>`}
function openModal(html){document.getElementById('modal').innerHTML=html;document.getElementById('modalWrap').classList.add('open')}
function closeModal(){document.getElementById('modalWrap').classList.remove('open');pendingPhoto=null}
function backdropClose(e){if(e.target.id==='modalWrap')closeModal()}
render();
