// Map-driven product layer. This file intentionally overrides the earlier demo logic.
const MAP_KITCHEN=['Холодные закуски','Салаты','Горячие закуски','Супы','Горячие блюда','Десерты'];
const MAP_BAR=['Вино','Коктейли','Крепкий алкоголь','Кофе / чай','Безалкогольные напитки'];
function ensureMapStock(){
  const sampleK={price:'590 ₽',weight:'220 г',desc:'Красочное описание блюда для обучения сотрудника.',ingredients:'Основные ингредиенты позиции',taste:'',allergens:'',pair:'',photo:''};
  const sampleB={price:'590 ₽',volume:'125 мл',strength:'—',desc:'Красочное описание напитка для обучения сотрудника.',ingredients:'Основные ингредиенты позиции',taste:'Вкус позиции',serve:'Подача',glass:'Бокал',photo:''};
  MAP_KITCHEN.forEach((b,i)=>{if(!STOCK.kitchen.some(x=>x.block===b))STOCK.kitchen.push({id:'mk'+i,area:'kitchen',block:b,name:b==='Салаты'?'Салат с томатами':b==='Супы'?'Крем-суп':b==='Десерты'?'Десерт дня':b==='Горячие блюда'?'Горячее блюдо':b==='Горячие закуски'?'Горячая закуска':'Холодная закуска',...sampleK})});
  MAP_BAR.forEach((b,i)=>{if(!STOCK.bar.some(x=>x.block===b))STOCK.bar.push({id:'mb'+i,area:'bar',block:b,name:b==='Вино'?'Sauvignon Blanc':b==='Коктейли'?'Negroni':b==='Крепкий алкоголь'?'Bourbon':b==='Кофе / чай'?'Фильтр-кофе':'Домашний тоник',...sampleB})});
}
ensureMapStock();
function blocksFor(area){return area==='kitchen'?MAP_KITCHEN:MAP_BAR}
function status(){return ''}
function activeEmployees(){return state.employees.filter(e=>e.active!==false)}
function teamRating(){return avg(activeEmployees().map(e=>rating(e)).filter(Boolean))}
state.managerPin=state.managerPin||'0000';
state.filter=state.filter||'Все';
state.learnArea=state.learnArea||'kitchen';
state.auth=null;
activeEmployees().forEach((e,i)=>{if(!/^\d{4}$/.test(e.pin||''))e.pin=String(1111+i*1111).slice(0,4)});
if(!['roles','manager-pin','staff-select','staff-pin'].includes(state.route)) state.route='roles';
save();

function roleCards(){return `<section class="managerhero"><div class="kicker">Главное меню</div><h1>Выберите кабинет</h1><p>Управляющий контролирует команду и аттестации. Официант и бармен изучают кухню и бар.</p></section><section class="section"><div class="grid g3"><button class="card" onclick="openRole('Управляющий')"><span class="badge">01</span><h3>Управляющий</h3><p class="small-muted">Команда · рейтинг · сотрудники · аттестации</p></button><button class="card" onclick="openRole('Официант')"><span class="badge">02</span><h3>Официант</h3><p class="small-muted">Кухня · бар · обучение · личный рейтинг</p></button><button class="card" onclick="openRole('Бармен')"><span class="badge">03</span><h3>Бармен</h3><p class="small-muted">Бар · кухня · обучение · личный рейтинг</p></button></div></section>`}
function openRole(role){state.role=role;state.auth=null;if(role==='Управляющий'){state.route='manager-pin'}else{state.route='staff-select'};save();render()}
function managerPinPage(){return `<section class="managerhero"><div class="kicker">Управляющий</div><h1>PIN-код</h1><p>Вход в кабинет управляющего.</p></section><section class="section"><div class="card" style="max-width:480px;margin:auto"><div class="field"><label>4 цифры</label><input id="mgrPin" inputmode="numeric" maxlength="4" placeholder="••••"></div><div class="split-actions"><button class="primary" onclick="checkManagerPin()">Войти</button><button class="ghost" onclick="goRoles()">Назад</button></div><p class="small-muted">Демо: 0000</p></div></section>`}
function checkManagerPin(){if((document.getElementById('mgrPin').value||'')!==state.managerPin){alert('Неверный PIN');return}state.auth='manager';state.route='home';save();render()}
function staffSelectPage(){const xs=activeEmployees().filter(e=>e.role===state.role);return `<div class="head"><div><h2>${esc(state.role)}</h2><p>Выберите сотрудника</p></div><button class="ghost" onclick="goRoles()">Назад</button></div><div class="team-grid">${xs.map(e=>`<button class="card employee" onclick="selectStaff('${e.id}')">${employeePhoto(e)}<div><h3>${esc(e.name)}</h3><p>${esc(e.role)}</p></div><div class="emp-score"><strong>${rating(e)||'—'}${rating(e)?'%':''}</strong><span>рейтинг</span></div></button>`).join('')||'<div class="empty">Нет сотрудников этой должности.</div>'}</div>`}
function selectStaff(id){state.currentEmployee=id;state.route='staff-pin';save();render()}
function staffPinPage(){const e=current();return `<section class="managerhero"><div class="kicker">${esc(e.role)}</div><h1>${esc(e.name)}</h1><p>Введите PIN-код сотрудника.</p></section><section class="section"><div class="card" style="max-width:480px;margin:auto"><div class="field"><label>4 цифры</label><input id="staffPin" inputmode="numeric" maxlength="4" placeholder="••••"></div><div class="split-actions"><button class="primary" onclick="checkStaffPin()">Войти</button><button class="ghost" onclick="state.route='staff-select';render()">Назад</button></div><p class="small-muted">Демо: ${esc(e.pin)}</p></div></section>`}
function checkStaffPin(){const e=current();if((document.getElementById('staffPin').value||'')!==e.pin){alert('Неверный PIN');return}state.auth='staff';state.route='home';save();render()}
function goRoles(){state.auth=null;state.route='roles';save();render()}

function nav(){if(state.route==='roles'||state.route==='manager-pin'||state.route==='staff-select'||state.route==='staff-pin')return '';if(state.auth==='manager')return [['home','⌂','Команда']].map(([r,i,l])=>`<button class="on" onclick="go('home')"><b>${i}</b>${l}</button>`).join('')+`<button onclick="openEmployeeForm()"><b>＋</b>Добавить</button><button onclick="document.getElementById('archiveBox')?.scrollIntoView({behavior:'smooth'})"><b>□</b>Архив</button><button onclick="goRoles()"><b>↩</b>Выйти</button>`;return `<button class="${state.route==='home'?'on':''}" onclick="go('home')"><b>⌂</b>Кабинет</button><button class="${state.route==='learn'&&state.learnArea==='kitchen'?'on':''}" onclick="state.learnArea='kitchen';go('learn')"><b>◫</b>Кухня</button><button class="${state.route==='learn'&&state.learnArea==='bar'?'on':''}" onclick="state.learnArea='bar';go('learn')"><b>◒</b>Бар</button><button onclick="goRoles()"><b>↩</b>Выйти</button>`}
const oldRender=render;
render=function(){
  document.getElementById('roleBtn').textContent=state.route==='roles'?'Главное меню':state.role;
  document.getElementById('roleBtn').onclick=goRoles;
  const e=current();document.getElementById('topAvatar').innerHTML=e?.photo?`<img src="${esc(e.photo)}">`:e?initials(e.name):'RA';
  document.getElementById('nav').innerHTML=nav();
  let html='';if(state.route==='roles')html=roleCards();else if(state.route==='manager-pin')html=managerPinPage();else if(state.route==='staff-select')html=staffSelectPage();else if(state.route==='staff-pin')html=staffPinPage();else html=state.auth==='manager'?renderManager():renderStaff();document.getElementById('root').innerHTML=html;
};

function renderStaff(){if(state.route==='learn')return learnPage();return staffHome()}
function staffHome(){const e=current(),all=rating(e),kr=rating(e,'kitchen'),br=rating(e,'bar');return `<section class="hero"><div><div class="kicker">${esc(e.role)} · кабинет</div><h1>${esc(e.name)}</h1><p>Рейтинг формируется только из нескольких аттестаций. Тренировочные тесты его не меняют.</p><div class="split-actions"><button class="secondary ghost" onclick="openSelfPhoto()">Изменить фото</button></div></div><div class="scorebox"><span>Мой рейтинг</span><strong>${all||'—'}${all?'%':''}</strong><div class="track"><i style="width:${all}%"></i></div><small>${atts(e).length} аттестаций</small></div></section><section class="section"><div class="grid g2">${staffAreaCard(e,'kitchen','Кухня',kr)}${staffAreaCard(e,'bar','Бар',br)}</div></section>`}
function staffAreaCard(e,area,title,r){return `<button class="card area-card" onclick="state.learnArea='${area}';go('learn')"><div class="area-top"><div><span class="badge">Рейтинг ${title.toLowerCase()}</span><h3>${title}</h3></div><b>${r?r+'%':'—'}</b></div><div class="track"><i style="width:${r}%"></i></div><div class="blocks">${blocksFor(area).map(b=>`<div class="blockrow"><div><b>${esc(b)}</b><small>${atts(e,area,b).length} аттестаций</small></div><strong>${rating(e,area,b)||'—'}${rating(e,area,b)?'%':''}</strong></div>`).join('')}</div></button>`}
function learnPage(){const area=state.learnArea||'kitchen',title=area==='kitchen'?'Кухня':'Бар';return `<div class="head"><div><h2>${title}</h2><p>Меню по блокам</p></div><button class="ghost" onclick="go('home')">Назад</button></div><div class="toolbar">${blocksFor(area).map((b,i)=>`<button class="chip ${i===0?'on':''}" onclick="showBlock('${area}','${esc(b)}')">${esc(b)}</button>`).join('')}</div><div class="test-note">Тренировочные тесты по позиции, блоку и всему разделу рейтинг не меняют. Их механику проектируем отдельно.</div><section class="section"><div id="menuBlock">${blockHTML(area,blocksFor(area)[0])}</div></section><div class="split-actions"><button class="primary" onclick="practicePlaceholder('${title} · весь раздел')">Пройти тест по всему ${title.toLowerCase()}</button></div>`}
function showBlock(area,block){document.getElementById('menuBlock').innerHTML=blockHTML(area,block);document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('on',x.textContent===block))}
function blockHTML(area,block){const xs=STOCK[area].filter(x=>x.block===block);return `<div class="head"><div><h2>${esc(block)}</h2><p>Список позиций для изучения</p></div><button class="ghost" onclick="practicePlaceholder('${esc(block)}')">Тест по блоку</button></div><div class="menu-grid">${xs.map(menuCard).join('')}</div>`}
function openMenu(id){const x=findMenu(id);if(!x)return;const bar=x.area==='bar';openModal(`<div class="modal-head"><div><div class="kicker">${bar?'Бар':'Кухня'} · ${esc(x.block)}</div><h2>${esc(x.name)}</h2><p>${esc(x.desc)}</p></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="detail-photo">${x.photo?`<img src="${x.photo}" onerror="this.style.display='none'">`:''}</div><div class="facts"><div class="fact"><span>Цена</span><b>${esc(x.price)}</b></div><div class="fact"><span>${bar?'Объём':'Вес'}</span><b>${esc(x.volume||x.weight||'—')}</b></div>${bar?`<div class="fact"><span>Крепость</span><b>${esc(x.strength||'—')}</b></div><div class="fact"><span>Вкус</span><b>${esc(x.taste||'—')}</b></div><div class="fact"><span>Подача</span><b>${esc(x.serve||'—')}</b></div><div class="fact"><span>Бокал</span><b>${esc(x.glass||'—')}</b></div>`:''}<div class="fact"><span>Основной состав</span><b>${esc(x.ingredients||'—')}</b></div></div><div class="modal-actions"><button class="primary" onclick="practicePlaceholder('${esc(x.name)}')">Пройти тест по ${bar?'позиции':'блюду'}</button></div>`)}
function practicePlaceholder(label){openModal(`<div class="modal-head"><div><div class="kicker">Тренировочный тест</div><h2>${esc(label)}</h2></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="notice">Механику тестов специально пока не придумываем. Зафиксировано только правило: тренировочный тест не меняет рейтинг.</div>`)}
function openSelfPhoto(){const e=current();openModal(`<div class="modal-head"><div><div class="kicker">Фото сотрудника</div><h2>${esc(e.name)}</h2></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="field"><label>Новое фото</label><input id="selfPhoto" type="file" accept="image/*"></div><div class="modal-actions"><button class="primary" onclick="saveSelfPhoto()">Сохранить</button></div>`)}
function saveSelfPhoto(){const f=document.getElementById('selfPhoto').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{current().photo=r.result;save();closeModal();render()};r.readAsDataURL(f)}

function renderManager(){return managerHome()}
function managerHome(){const xs=activeEmployees().filter(e=>state.filter==='Все'||e.role===state.filter);const archived=state.employees.filter(e=>e.active===false);return `<section class="managerhero"><div class="kicker">Кабинет управляющего</div><h1>Команда</h1><p>Общий рейтинг команды — только по аттестациям сотрудников.</p></section><section class="section"><div class="card metric"><span>Общий рейтинг всей команды</span><strong>${teamRating()||'—'}${teamRating()?'%':''}</strong><div class="track"><i style="width:${teamRating()}%"></i></div><small>Среднее значение результатов активной команды</small></div></section><section class="section"><div class="head"><div><h2>Сотрудники</h2><p>Все зарегистрированные участники программы</p></div><button class="primary" onclick="openEmployeeForm()">+ Добавить сотрудника</button></div><div class="toolbar">${['Все','Официант','Бармен'].map(f=>`<button class="chip ${state.filter===f?'on':''}" onclick="state.filter='${f}';render()">${f==='Официант'?'Официанты':f==='Бармен'?'Бармены':'Все'}</button>`).join('')}</div><div class="team-grid">${xs.map(employeeCard).join('')}</div></section><section class="section" id="archiveBox"><div class="head"><div><h2>Архив</h2><p>История и аттестации сохраняются</p></div></div>${archived.length?archived.map(e=>`<div class="card" style="margin-bottom:8px"><b>${esc(e.name)}</b> · ${esc(e.role)} <button class="ghost" onclick="eRestore('${e.id}')">Вернуть</button></div>`).join(''):'<div class="empty">Архив пуст</div>'}</section>`}
function employeeCard(e){return `<div class="card employee">${employeePhoto(e)}<div><h3>${esc(e.name)}</h3><p>${esc(e.role)} · ${e.phone?`<a href="tel:${esc(e.phone.replace(/\s/g,''))}">${esc(e.phone)}</a>`:''} ${e.tg?'· '+esc(e.tg):''}</p><div class="emp-ratings"><span class="mini-rating">Кухня ${rating(e,'kitchen')||'—'}%</span><span class="mini-rating">Бар ${rating(e,'bar')||'—'}%</span><span class="mini-rating">${atts(e).length} атт.</span></div></div><div class="emp-score"><strong>${rating(e)||'—'}${rating(e)?'%':''}</strong><span>общий рейтинг</span></div><div class="employee-actions"><button class="primary" onclick="openEmployeeManager('${e.id}')">Управление</button><button class="ghost" onclick="openEmployeeForm('${e.id}')">Редактировать</button></div></div>`}
function manageArea(e,area,title,r){return `<div class="card" style="box-shadow:none"><div class="area-top"><div><span class="badge">${title}</span><h3>${title}</h3></div><b>${r?r+'%':'—'}</b></div><div class="track" style="margin:10px 0"><i style="width:${r}%"></i></div><div class="blocks">${blocksFor(area).map(b=>`<div class="blockrow"><div><b>${esc(b)}</b><small>шкала знания · ${atts(e,area,b).length} атт.</small><div class="track" style="margin-top:5px"><i style="width:${rating(e,area,b)}%"></i></div></div><div><strong>${rating(e,area,b)||'—'}${rating(e,area,b)?'%':''}</strong><div class="split-actions"><button class="ghost" onclick="practicePlaceholder('${esc(b)}')">Тест</button><button class="primary" onclick="attestationPlaceholder('${e.id}','${area}','${esc(b)}')">Аттестация</button></div></div></div>`).join('')}</div></div>`}
function attestationPlaceholder(id,area,block){openModal(`<div class="modal-head"><div><div class="kicker">Аттестация</div><h2>${esc(block)}</h2></div><button class="closebtn" onclick="openEmployeeManager('${id}')">×</button></div><div class="notice">Механику аттестации проектируем отдельно. Зафиксировано: результат аттестации влияет на рейтинг; рейтинг формируется из нескольких аттестаций; тренировки рейтинг не меняют.</div>`)}
function attList(e,limit){const rows=[...atts(e)].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit);if(!rows.length)return `<div class="empty">Аттестаций пока нет.</div>`;return `<div class="list">${rows.map(a=>`<div class="att-row"><div><b>${esc(a.block)}</b><small>${a.area==='kitchen'?'Кухня':'Бар'} · ${esc(a.date)}</small></div><div class="att-score">${a.score}%</div></div>`).join('')}</div>`}
function openEmployeeManager(id){state.currentEmployee=id;save();const e=emp(id);openModal(`<div class="modal-head"><div><div class="kicker">Управление сотрудником</div><h2>${esc(e.name)}</h2><p>${esc(e.role)} · общий рейтинг ${rating(e)||'—'}${rating(e)?'%':''}</p></div><button class="closebtn" onclick="closeModal()">×</button></div><div class="grid g2" style="margin-top:14px">${manageArea(e,'kitchen','Кухня',rating(e,'kitchen'))}${manageArea(e,'bar','Бар',rating(e,'bar'))}</div><section class="section"><div class="head"><div><h2>История аттестаций</h2><p>Несколько аттестаций формируют рейтинг. Тренировки не входят.</p></div></div>${attList(e,50)}</section><section class="section"><div class="split-actions"><button class="ghost" onclick="openPinReset('${e.id}')">Сменить / сбросить PIN</button><button class="ghost" onclick="openEmployeeForm('${e.id}')">Редактировать сотрудника</button><button class="danger" onclick="archiveEmployee('${e.id}')">Архивировать</button></div></section>`)}
function archiveEmployee(id){if(!confirm('Архивировать сотрудника? История сохранится.'))return;emp(id).active=false;save();closeModal();render()}
function eRestore(id){emp(id).active=true;save();render()}
function deleteEmployee(id){archiveEmployee(id)}
render();