// Employee overview -> full employee page. No new rating mechanics.
function latestAttestation(e){const rows=[...(e?.attestations||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));return rows[0]||null}
function employeeCard(e){const last=latestAttestation(e),r=rating(e);return `<button class="employee-compact" onclick="openEmployeePage('${e.id}')">${employeePhoto(e)}<div class="employee-compact-main"><h3>${esc(e.name)}</h3><p>${esc(e.role)}${e.tg?' · '+esc(e.tg):''}</p><div class="emp-ratings"><span class="mini-rating">Кухня ${rating(e,'kitchen')||'—'}%</span><span class="mini-rating">Бар ${rating(e,'bar')||'—'}%</span><span class="mini-rating">${atts(e).length} атт.</span></div><div class="employee-last">${last?`Последняя аттестация: ${esc(last.date)} · ${esc(last.block)} · ${last.score}%`:'Аттестаций пока нет'}</div></div><div class="employee-compact-score"><strong>${r||'—'}${r?'%':''}</strong><small>общий рейтинг</small></div><span class="employee-compact-arrow">›</span></button>`}
function openEmployeePage(id){state.currentEmployee=id;state.route='employee-detail';save();closeModal();render();window.scrollTo({top:0,behavior:'auto'})}
function renderManager(){if(state.route==='employee-detail')return employeeDetailPage();return managerHome()}
function knowledgeRows(e,area){return blocksFor(area).map(b=>{const r=rating(e,area,b),n=atts(e,area,b).length;return `<div class="knowledge-row"><div><b>${esc(b)}</b><small>${n?`${n} аттестаци${n===1?'я':'и'}`:'аттестаций пока нет'}</small></div><strong>${r?r+'%':'—'}</strong></div>`}).join('')}
function employeeHistory(e){const rows=[...atts(e)].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));if(!rows.length)return '<div class="empty">Аттестаций пока нет.</div>';return `<div class="history-card">${rows.map(a=>`<div class="history-row"><time>${esc(a.date)}</time><div><b>${esc(a.block)}</b><small>${a.area==='kitchen'?'Кухня':'Бар'}</small></div><strong>${a.score}%</strong></div>`).join('')}</div>`}
function employeeDetailPage(){const e=current(),all=rating(e),kr=rating(e,'kitchen'),br=rating(e,'bar');return `<div class="backline"><button class="ghost" onclick="state.route='home';save();render()">← Команда</button></div><section class="employee-detail-head">${employeePhoto(e)}<div><div class="kicker">${esc(e.role)} · сотрудник</div><h1>${esc(e.name)}</h1><p>${e.phone?esc(e.phone):''}${e.tg?`${e.phone?' · ':''}${esc(e.tg)}`:''}${e.start?`${e.phone||e.tg?' · ':''}с ${esc(e.start)}`:''}</p></div><div class="detail-total"><span>Общий рейтинг</span><strong>${all||'—'}${all?'%':''}</strong></div></section><section class="section section-lined"><div class="section-title"><span>01</span><div><h2>Знания</h2><p>Из чего складывается текущий рейтинг сотрудника</p></div></div><div class="knowledge-grid"><div class="knowledge-card"><div class="knowledge-head"><h3>Кухня</h3><strong>${kr?kr+'%':'—'}</strong></div><div class="knowledge-list">${knowledgeRows(e,'kitchen')}</div></div><div class="knowledge-card"><div class="knowledge-head"><h3>Бар</h3><strong>${br?br+'%':'—'}</strong></div><div class="knowledge-list">${knowledgeRows(e,'bar')}</div></div></div></section><section class="section section-lined"><div class="section-title"><span>02</span><div><h2>История аттестаций</h2><p>Все результаты, которые участвуют в рейтинге</p></div></div>${employeeHistory(e)}</section><section class="section section-lined"><div class="settings-strip"><div><b>Настройки сотрудника</b><small>Редко используемые действия</small></div><div class="settings-actions"><button class="ghost" onclick="openEmployeeForm('${e.id}')">Редактировать</button><button class="ghost" onclick="openPinReset('${e.id}')">Сменить PIN</button><button class="danger" onclick="archiveEmployee('${e.id}')">Архивировать</button></div></div></section>`}
render();
